# Generated by Django 6.0.2 on 2026-07-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='form',
            name='google_sheet_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='synced_to_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
